name = "ask"
version = "0.1.1"

description = "Utilities for composing predicates and equivalence relations"
licences = ["MIT"]
repository = { type = "github", user = "furrycatherder", repo = "gleam-ask" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
